### DISCUSSION TITLE
Connect-go with Istio

### DISCUSSION THREAD

**Discussion by ymmt2005** [connectrpc/connect-go#619] [Q&A] [answered]
Hello,

We use connect-go almost successfully to multiplex gRPC/gRPC-Web/Connect protocols.
One remaining problem is that when we use connect-go enabled service with Istio,
it cannot work with `appProtocol: grpc` in their Service.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: bar
spec:
  selector:
    app: foo
  ports:
  - name: grpc-h2c
    port: 8080
    targetPort: connect
    protocol: TCP
    appProtocol: grpc
```

The client is on the same Kubernetes cluster and connecting the service with gRPC.

```go
        client := foo.NewFooClient(httpClient, "http://foo.bar.svc:8080",
                connect.WithGRPC(),
        )
```

We only got `protoc error no Grpc-Status trailer: unexpected EOF` errors.
If we change the above `appProtocol: tcp`, it works.

Does anyone have any information?
