### ISSUE TITLE
Connect RPC import path being the Buf-tour path

### ISSUE THREAD

**Issue by sudowoodo200** [connectrpc/connect-go#736]
**Describe the bug**

`.connect.go` file imports `.pb.go` file as `v1 "github.com/bufbuild/buf-tour/gen/v1"`. Totally wrong. I believe it's because my proto directory has "v1"

**To Reproduce**

buf.gen.yaml
``` yaml
   - plugin: buf.build/protocolbuffers/go
    out: go/pkgs/bindings/proto
    opt:
      - paths=source_relative
  - plugin: buf.build/connectrpc/go
    out: go/pkgs/bindings/proto
    opt:
      - paths=source_relative
```

command
```bash
buf generate --path ./v1/*.proto
```

Results:
```go
// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/test.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bufbuild/buf-tour/gen/v1"
	http "net/http"
	strings "strings"
)
```

**Additional context**
