### ISSUE TITLE
generated code won't compile

### ISSUE THREAD

**Issue by duongphuhiep** [connectrpc/connect-go#785]
**Describe the bug**

Generated code won't compile

![image](https://github.com/user-attachments/assets/9aaf387b-b0a8-492d-89c0-eb012bb33cb1) 

**To Reproduce**

Following the docs: https://connectrpc.com/docs/go/getting-started/

- your complete `go.mod`:
```
module starfruit.golesson

go 1.23.1

require (
	connectrpc.com/connect v1.17.0 // indirect
	golang.org/x/net v0.30.0 // indirect
	golang.org/x/text v0.19.0 // indirect
	google.golang.org/protobuf v1.34.2 // indirect
)
```

**Comment by jhump** [comment]
Compilation errors in generated code are generally due to configuration errors.

In this case, it seems that the Go package option in the Protobuf source file (or `managed` stanza in `buf.gen.yaml` if you use the Buf CLI and its "Managed Mode" feature) is incorrect. In particular, it looks like you may have used an empty string as the Go package prefix in Managed Mode configuration.

**Comment by duongphuhiep** [comment]
if I put "starfruit.golesson" as go package prefix then it will generate a folder "gen/starfruit.golesson/..." and the import won't work.. But I finally solved the problem

1) put "starfruit.golesson" as go package prefix
2) put `opt: paths=source_relative` evens if the plugin documentation tell you it was the "default options"

I can say that `buf generate` will never generate compiled codes without `opt: paths=source_relative` in the `buf.gen.yaml`

```yaml
version: v2
managed:
  enabled: true
plugins:
  - remote: buf.build/protocolbuffers/go:v1.34.2
    out: gen
    opt: paths=source_relative
  - remote: buf.build/connectrpc/go:v1.17.0
    out: gen
    opt: paths=source_relative
```
