### ISSUE TITLE
Documentation opts to opt in buf version 2 configurations

### ISSUE THREAD

**Issue by adlion** [connectrpc/connect-go#815]
**Describe the bug**
On golang package documentation it is declared as `opts` while the correct is `opt` for version 2

```yaml
version: v2
plugins:
  - local: protoc-gen-go
    out: gen
  - local: protoc-gen-connect-go
    out: gen
    opts: package_suffix
```

it should be 
```yaml
version: v2
plugins:
  - local: protoc-gen-go
    out: gen
  - local: protoc-gen-connect-go
    out: gen
 HERE >>>>   opt: package_suffix
```
